export const SET_USERS_LIST = "SET_USERS_LIST";
export const CLEAR_USER_LIST = "CLEAR_USER_LIST";
export const ERROR_USER_LIST = "ERROR_USER_LIST";
export const SET_AUTH_TOKEN = "SET_AUTH_TOKEN";
export const SET_SIGNUP_ERROR = "SET_SIGNUP_ERROR";
export const SET_LOGIN_ERROR = "SET_LOGIN_ERROR";
export const AUTH_FETCHING_START = "AUTH_FETCHING_START";
export const START_USER_INFO = "START_USER_INFO";
export const SET_USER_INFO_ERROR = "SET_USER_INFO_ERROR";
export const SET_USER_INFO = "SET_USER_INFO";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const TRANSACTION_FETCHING = "TRANSACTION_FETCHING";
export const TRANSACTION_INFO_SET = "TRANSACTION_INFO_SET";
export const TRANSACTION_INFO_SET_ERROR = "TRANSACTION_INFO_SET_ERROR";

export const TRANSACTION_LIST_FETCHING = "TRANSACTION_LIST_FETCHING";
export const TRANSACTION_LIST_SET = "TRANSACTION_LIST_SET";
export const TRANSACTION_LIST_ERROR = "TRANSACTION_LIST_ERROR";

export const TRANSACTION_REPLAY_SET = "TRANSACTION_REPLAY_SET";

export const INSTRUMENTS_LOADING = "INSTRUMENTS_LOADING";
export const INSTRUMENTS_ERROR = "INSTRUMENTS_ERROR";
export const INSTRUMENTS_SET = "INSTRUMENTS_SET";
